image: markhobson/node-chrome

stages:
  - install
  - test
  - build
  - report

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

linting_application:
  stage: test
  script:
    - npm run lint
  allow_failure: true

build_application:
  stage: build
  script:
    - npm run public
  artifacts:
    paths:
      - public/
  allow_failure: true

lighthouse_report:
  stage: report
  variables:
  before_script:
    - npm i -g pm2
    - npm i -g lighthouse
    - npm run pm2-serve
  scripts: 
    - npm run generate-report
    - npm run weblint
  artifacts:
    paths:
      - ./report.html
    expire_in: 1 week
